### ISSUE TITLE
[Packaging Issue] Tests folder is packaged with pytest-archon

### ISSUE THREAD

**Issue by ThirVondukr** [jwbargsten/pytest-archon#32]
Seems like tests directory is packaged with library, you probably should limit published directories to `pytest_archon`, I discovered a similar issue with my library: https://gitlab.com/ThirVondukr/aioinject/-/blob/96d5c288b8cf6de07a12b1ab4aa2a22800997b54/pyproject.toml#L45
![image](https://github.com/jwbargsten/pytest-archon/assets/50728601/2cd2ddb0-d3d1-4149-a239-691d459861c9)

*Clarification: It's not a problem that it's packaged with the library but it's considered a source directory and is importable

**Comment by jwbargsten** [comment]
I think I'll leave it like this. The `tests/` folder is added by [setuptools by default](https://github.com/pypa/setuptools/blob/e92440ad6210b21f3ede64d7eb69dead94b37d3a/setuptools/_distutils/command/sdist.py#L237) and my approach is: leave it at default if there is no strong indication that it needs to be changed. Most packages include tests in their source distributions.

**Comment by ThirVondukr** [comment]
The issue is it's importable with just `import tests` 👀

**Comment by jwbargsten** [comment]
Then I need more details:
* how do you download it
* how do you install it
* example script where you can import it as "tests", is your script in the same directory as the source?

**Comment by ThirVondukr** [comment]
- Create a venv
- Activate it
- Install pytest-archon with `pip install pytest_archon`
```py
(.venv)
doctor@main MINGW64 /c/dev/pytest-archon-test
$ python
Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytest_archon
>>> import tests
>>> dir(tests)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> from tests import test_collect
>>> print(test_collect)
<module 'tests.test_collect' from 'C:\\dev\\pytest-archon-test\\.venv\\Lib\\site-packages\\tests\\test_collect.py'>
```

**Comment by jwbargsten** [comment]
confirmed, nice find!

**Comment by jwbargsten** [comment]
<img width="746" alt="image" src="https://github.com/jwbargsten/pytest-archon/assets/919322/ecf5f40a-8bb1-4f7c-81b8-4700f431c8b8">
